---
 - hosts: all
   become: yes
   tasks: 
   - name: find the list of files
     find:
       path: /home/ansible
       file_type: directory
     register: out
   - name: print
     debug:
       msg: "{{ out.files }}"
   - name: delete the files
     file:
       path: "{{ item.path }}"
       state: absent
     loop: "{{ out.files }}"
