---
 - hosts: all
   become: yes
   tasks: 
   - name: blockinfile
     blockinfile:
       path: /tmp/file1.txt
       state: absent
       block:
         line1
         line2
         line3
         line4
