---
 - hosts: rd
   become: yes
   tasks:
   - name: installing multiple packages
     user:
       name: "{{ item }}"
       password: "admin123"
     loop:
       - madu
       - appu
       - swapna
       - madhu
