---
 - hosts: all
   become: yes
   tasks:
   - name: install apache2
     apt:
       name: apache2
       state: present
     when: ansible_distribution == "ubuntu"
   - name: install httpd
     yum:
       name: httpd
       state: present
     when: ansible_distribution == "RedHat"
